<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
     public function run()
  {
     DB::table('products')->insert([
       [
         'id' => '1',
         'name' => '洋風ミックス弁当',
         'price' => '500',
         'discount' => '200',
         'pic1' => '1x8bozNH4RHlGv7TcvpXu0pJss8WJxi2RFrn11m1.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '23',
         'hour' => '21',
         'expiration' => '2020-05-23',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '1',
         'company_id' => '2',
       ],
       [
         'id' => '2',
         'name' => 'とり天マヨおにぎり',
         'price' => '120',
         'discount' => '50',
         'pic1' => '8FhE32u6AOiilMamiGWuhsX8WDEHRKAB1oyIrTLq.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '24',
         'hour' => '0',
         'expiration' => '2020-05-24',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '5',
         'company_id' => '3',
       ],
       [
         'id' => '3',
         'name' => 'テリヤキチキンとたまごチキン',
         'price' => '230',
         'discount' => '80',
         'pic1' => '8uIWnIRWaa7sBmU21c5BFiGvSAZomLxin4lSSdpQ.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '25',
         'hour' => '0',
         'expiration' => '2020-05-25',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '4',
         'company_id' => '1',
       ],
       [
         'id' => '4',
         'name' => '塩おにぎり',
         'price' => '120',
         'discount' => '40',
         'pic1' => '9R1e6G794nQOGJKI4RiVk28l4LhpjQOLLZtATmoY.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '26',
         'hour' => '21',
         'expiration' => '2020-05-26',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '5',
         'company_id' => '1',
       ],
       [
         'id' => '5',
         'name' => '若鳥のニンニク唐揚げ弁当',
         'price' => '480',
         'discount' => '200',
         'pic1' => '18PzHxV6zksg4T3PVXMuFgRhHEV1yPFDm5778PJ7.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '27',
         'hour' => '21',
         'expiration' => '2020-05-27',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '1',
         'company_id' => '1',
       ],
       [
         'id' => '6',
         'name' => '明太子ときのことの和風パスタ',
         'price' => '480',
         'discount' => '220',
         'pic1' => '53cGeOfFETsE4PWBCMUFuBzEl7TXG1TM5yqWaFpA.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '28',
         'hour' => '21',
         'expiration' => '2020-05-28',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '3',
         'company_id' => '1',
       ],
       [
         'id' => '7',
         'name' => '銀鮭と和風おかずの幕の内弁当',
         'price' => '520',
         'discount' => '240',
         'pic1' => '67tCVKSkQ0vhBUdAY4r61IJhpr5Ce3ZrgYtN2UFp.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '29',
         'hour' => '21',
         'expiration' => '2020-05-29',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '1',
         'company_id' => '2',
       ],
       [
         'id' => '8',
         'name' => '食べる牧場いちご',
         'price' => '280',
         'discount' => '120',
         'pic1' => 'Ah0Zaux6KAPkYjO3ucuFhFZk9C5dP2UmF3QdbpqE.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '30',
         'hour' => '21',
         'expiration' => '2020-05-30',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '6',
         'company_id' => '2',
       ],
       [
         'id' => '9',
         'name' => 'チョリソー',
         'price' => '230',
         'discount' => '80',
         'pic1' => 'dGvETOiOmiqM9N2J3gW7c0ysC37Z2JFqIgpQg7xr.jpeg',
         'year' => '2020',
         'month' => '5',
         'day' => '31',
         'hour' => '11',
         'expiration' => '2020-05-31',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '4',
         'company_id' => '3',
       ],
       [
         'id' => '10',
         'name' => 'ピリ辛！スパイシージャンバラヤ',
         'price' => '390',
         'discount' => '150',
         'pic1' => 'dZRO05qF04aDHyBqwZTGQvP4Mi3FODxyYJ3S8Jgz.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '1',
         'hour' => '11',
         'expiration' => '2020-06-01',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '4',
         'company_id' => '2',
       ],
       [
         'id' => '11',
         'name' => '悪魔のおにぎり',
         'price' => '120',
         'discount' => '50',
         'pic1' => 'EtyuUcUJSjgNfZQ9IS7ihk0hPeX4vsHsGbHxDfEs.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '2',
         'hour' => '11',
         'expiration' => '2020-06-02',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '5',
         'company_id' => '3',
       ],
       [
         'id' => '12',
         'name' => '紀州南高梅おにぎり',
         'price' => '120',
         'discount' => '50',
         'pic1' => 'ggr9higQ49GHyoiPCesMVT6xyo7GjFWJXyzC4Kch.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '3',
         'hour' => '11',
         'expiration' => '2020-06-03',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '5',
         'company_id' => '2',
       ],
       [
         'id' => '13',
         'name' => '熟成サバおにぎり',
         'price' => '160',
         'discount' => '60',
         'pic1' => 'KLpeJ7snQFXqeJU3jOZ4eOpAg3V7IZMEKi5ccDO0.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '4',
         'hour' => '11',
         'expiration' => '2020-06-04',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '5',
         'company_id' => '2',
       ],
       [
         'id' => '14',
         'name' => 'もっと野菜　中華丼',
         'price' => '440',
         'discount' => '200',
         'pic1' => 'lGhMybpSbYQfZXwLH0YWLS4M9tD5eohCDX4dOPBd.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '5',
         'hour' => '11',
         'expiration' => '2020-06-05',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '1',
         'company_id' => '3',
       ],
       [
         'id' => '15',
         'name' => '家系ラーメン（豚骨醤油）',
         'price' => '490',
         'discount' => '200',
         'pic1' => 'LpBw82vPnaqt0siAjhhGsGyTlMZ7BZRLbjLDbxYF.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '7',
         'hour' => '11',
         'expiration' => '2020-06-07',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '3',
         'company_id' => '2',
       ],
       [
         'id' => '16',
         'name' => '伊右衛門茶 500ml',
         'price' => '160',
         'discount' => '90',
         'pic1' => 'nsN2b7OWIcRW0IyFJaBXiy9BkKayF9Ce3iXzjvYU.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '8',
         'hour' => '11',
         'expiration' => '2020-06-08',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '7',
         'company_id' => '1',
       ],
       [
         'id' => '17',
         'name' => '北海道のたらこパスタ',
         'price' => '400',
         'discount' => '150',
         'pic1' => 'VEy4x2lnlzxOXKzAexQYfIh5VVFwwanpB1uwXth8.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '9',
         'hour' => '11',
         'expiration' => '2020-06-09',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '3',
         'company_id' => '3',
       ],
       [
         'id' => '18',
         'name' => 'ざるそば',
         'price' => '400',
         'discount' => '170',
         'pic1' => 'za9PiVWCCGC72Up8m9MBw87Ht6JCmPOYXD9QV0E1.jpeg',
         'year' => '2020',
         'month' => '6',
         'day' => '10',
         'hour' => '11',
         'expiration' => '2020-06-10',
         'sold_flg' => '0',
         'delete_flg' => '0',
         'created_at' => Carbon::now(),
         'updated_at' => Carbon::now(),
         'category_id' => '3',
         'company_id' => '3',
       ]
     ]);
   }
}
